# Generated by Django 3.1.3 on 2020-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='images/')),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('attribute', models.CharField(choices=[('Author', 'Author'), ('Athlete', 'Athlete'), ('Politician', 'Politician')], max_length=10)),
                ('bio', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
