# Generated by Django 3.1.3 on 2020-12-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='attribute',
        ),
        migrations.AddField(
            model_name='author',
            name='attribute',
            field=models.ManyToManyField(to='author.Attribute'),
        ),
    ]
