# Generated by Django 3.1.3 on 2020-12-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20201211_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='attribute',
            field=models.ManyToManyField(blank=True, to='author.Attribute'),
        ),
    ]
