# Generated by Django 3.1.3 on 2021-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
