# Generated by Django 3.1.3 on 2021-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_facebook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
