# Generated by Django 3.1.3 on 2021-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quoteofday'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteofday',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
