# Generated by Django 3.1.3 on 2020-12-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20201211_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
